# Imagem base - Nginx alpine (Versão leve e otimizada)
FROM nginx:alpine

# Instrução para copiar os arquivos do diretorio "X" para a imagem
COPY . /usr/share/nginx/html

# Expondo a porta de acesso
EXPOSE 80

# Verificação da saúde do sistema
HEALTHCHECK --interval=30s --timeout=3s \
  CMD wget -q --spider http://localhost || exit 1

# Comandos CMD para confgurações personalizadas
CMD [ "nginx", "-g", "daemon off;"]