name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        run: docker build -t statusboard:v1.0 ./app

      - name: Rodar o container
        run: docker run -d -p 8080:80 --name statusboard statusboard

      - name: Verificar se a aplicação responde
        run: |
          sleep 3
          curl --fail http://localhost:8080 || exit 1

      - name: Parar o container
        run: docker stop statusboard
